const menu = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'D',
      price: 15.99,
      img: './images/item-1.png',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'dunno',
      category: 'E',
      price: 13.99,
      img: './images/item-2.png',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'N',
      price: 6.99,
      img: './images/item-3.png',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'G',
      price: 20.99,
      img: './images/item-4.png',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
 
    {
      id: 6,
      title: 'oreo dream',
      category: ' H',
      price: 18.99,
      img: './images/item-6.png',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: ' E',
      price: 8.99,
      img: './images/item-7.png',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'american classic',
      category: ' M',
      price: 12.99,
      img: './images/item-8.png',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'America Reports',
      category: ' J',
      price: 51,
      img: './images/item-9.webp',
      desc: `cue 51. Sandra always gets an eyelight.`,
    },
    {
        id: 10,
        title: 'Americas Newsroom',
        category: ' J',
        price: 20,
        img: './images/item-11.jpeg',
        desc: `cue 20,turn subs g1 g2, g1+g2 inclusive.`,
      },
  ];
  export default menu;